### ISSUE TITLE
RSS as data source

### ISSUE THREAD

**Issue by ninjatrench** [ninjatrench/DeveloperHorizon#10]
Add remote RSS url as data source for data aggregation.

**Comment by ninjatrench** [comment]
Kindly share some links of demo data sources so I can look into how to parse them

**Comment by irl** [comment]
RSS example: http://lwn.net/headlines/newrss
RSS example: https://www.debian.org/News/news
ATOM example: https://www.gentoo.org/feeds/news.xml
