### ISSUE TITLE
horizon.debian.net needs migrating to a VM

### ISSUE THREAD

**Issue by irl** [ninjatrench/DeveloperHorizon#13]
Just filing this so we can block your deploying to this VM on this issue.

**Comment by ninjatrench** [comment]
Can you let me know the process for this ?

Thanks

**Comment by irl** [comment]
This is a task for me, not something for you. It's just here so I can remind myself it needs to be done.

I'm away for work until Wednesday, but I'm hoping to do this on Wednesday.

**Comment by irl** [comment]
I did not do this on Wednesday.
