### ISSUE TITLE
Documentation of API and Project

### ISSUE THREAD

**Issue by ninjatrench** [ninjatrench/DeveloperHorizon#6]
Pending parts :
Providing REST api documentation along with config files examples and guidelines for smoother execution

Providing automated shell script to manage dependency and installation of Developer Horizon project

**Comment by irl** [comment]
We can break this down into some parts:
- [x] User guide
- [x] API user guide
- [x] Deployment guide
- [x] Developers guide

**Comment by ninjatrench** [comment]
This looks good, I will fix this during the last week of GSOC

**Comment by ninjatrench** [comment]
Done. @irl 
https://github.com/ninjatrench/DeveloperHorizon/wiki
https://github.com/ninjatrench/DeveloperHorizon/wiki/API-guide
https://github.com/ninjatrench/DeveloperHorizon/wiki/Deployment-Guide
https://github.com/ninjatrench/DeveloperHorizon/wiki/Developer-Guide
